### ISSUE TITLE
MIT License vs ICS ?!

### ISSUE THREAD

**Issue by b2un0** [johnwoo-nl/emproto#1]
hey there,

many thanks for your code. the `clitest` works fine.

but, can you please fixe the license mismatch?

https://github.com/johnwoo-nl/emproto/blob/main/package.json#L15

thank you!

**Comment by johnwoo-nl** [comment]
Sure, the package.json is updated to also say MIT.
The ISC was just the npm init default, to get the code out as a package quickly.
